# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Fileme CV Theme"
license = "MIT"
licenselink = "https://github.com/fileme/fileme-cv-theme/blob/master/LICENSE"
description = "A theme for my CV"
homepage = "https://www.fileme.info/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Ahmed Hosny"
  homepage = "https://cv.fileme.info"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
